# Generated by Django 2.0.4 on 2018-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(default='cidade', max_length=20, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.TextField(default='00000-000', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.TextField(default='BR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(default='endereço', max_length=20, verbose_name='Endereço'),
        ),
    ]
