# Generated by Django 2.0.4 on 2018-04-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izap', '0003_auto_20180414_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default='estado', on_delete=django.db.models.deletion.PROTECT, to='izap.State', verbose_name='Estado'),
        ),
    ]
