# Generated by Django 2.0.4 on 2018-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izap', '0004_auto_20180414_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='CEPCOMPLETO', max_length=10, verbose_name='CEP'),
        ),
    ]
