# Generated by Django 2.0.4 on 2018-04-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izap', '0006_auto_20180414_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='izap.State', verbose_name='Estado'),
        ),
    ]
